# R Programming: Week 3 Notes - NPTEL

## 1. Power Operations

In [ ]:
print('--- Power Operations Examples ---')

# Using ^ operator
print(paste('2^3:', 2^3))
print(paste('2^0.5:', 2^0.5))
print(paste('2^-0.5:', 2^-0.5))

# Using ** operator
print(paste('2**3:', 2**3))
print(paste('2**0.5:', 2**0.5))

# Vector power operations
print(paste('c(2,3,5,7)^2:', c(2,3,5,7)^2))
print(paste('c(2,3,5,7)^c(2,3):', c(2,3,5,7)^c(2,3))) # Recycling c(2,3) to match length 4
print(paste('c(1,2,3,4,5,6)^c(2,3,4):', c(1,2,3,4,5,6)^c(2,3,4))) # Recycling c(2,3,4) to match length 6
print(paste('c(2,3,5,7)^c(2,3,4):', c(2,3,5,7)^c(2,3,4))) # Recycling c(2,3,4) to match length 4

[1] "--- Power Operations Examples ---"
[1] "2^3: 8"
[1] "2^0.5: 1.4142135623731"
[1] "2^-0.5: 0.707106781186548"
[1] "2**3: 8"
[1] "2**0.5: 1.4142135623731"
[1] "c(2,3,5,7)^2: 4"  "c(2,3,5,7)^2: 9"  "c(2,3,5,7)^2: 25" "c(2,3,5,7)^2: 49"
[1] "c(2,3,5,7)^c(2,3): 4"   "c(2,3,5,7)^c(2,3): 27"  "c(2,3,5,7)^c(2,3): 25" 
[4] "c(2,3,5,7)^c(2,3): 343"
[1] "c(1,2,3,4,5,6)^c(2,3,4): 1"    "c(1,2,3,4,5,6)^c(2,3,4): 8"   
[3] "c(1,2,3,4,5,6)^c(2,3,4): 81"   "c(1,2,3,4,5,6)^c(2,3,4): 16"  
[5] "c(1,2,3,4,5,6)^c(2,3,4): 125"  "c(1,2,3,4,5,6)^c(2,3,4): 1296"


Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”


[1] "c(2,3,5,7)^c(2,3,4): 4"   "c(2,3,5,7)^c(2,3,4): 27" 
[3] "c(2,3,5,7)^c(2,3,4): 625" "c(2,3,5,7)^c(2,3,4): 49" 


### Practice Task 1: Power Operations
Calculate the cube of each element in the vector `c(10, 20, 30)`.

In [ ]:
# Solution to Practice Task 1
vector_data <- c(10, 20, 30)
result <- vector_data^3
print(result)

[1]  1000  8000 27000


## 2. Integer Division

In [ ]:
print('--- Integer Division Examples (%%/%) ---')

# Scalar integer division
print(paste('2 %/% 2:', 2 %/% 2))
print(paste('5 %/% 2:', 5 %/% 2))
print(paste('7 %/% 3:', 7 %/% 3))

# Vector integer division
print(paste('c(2,3,5,7) %/% 2:', c(2,3,5,7) %/% 2))
print(paste('c(2,3,5,7) %/% c(2,3):', c(2,3,5,7) %/% c(2,3))) # Recycling c(2,3)
print(paste('c(2,3,5) %/% c(2,3):', c(2,3,5) %/% c(2,3))) # Recycling c(2,3), warning due to unequal lengths

[1] "--- Integer Division Examples (%%/%) ---"
[1] "2 %/% 2: 1"
[1] "5 %/% 2: 2"
[1] "7 %/% 3: 2"
[1] "c(2,3,5,7) %/% 2: 1" "c(2,3,5,7) %/% 2: 1" "c(2,3,5,7) %/% 2: 2"
[4] "c(2,3,5,7) %/% 2: 3"
[1] "c(2,3,5,7) %/% c(2,3): 1" "c(2,3,5,7) %/% c(2,3): 1"
[3] "c(2,3,5,7) %/% c(2,3): 2" "c(2,3,5,7) %/% c(2,3): 2"


Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”


[1] "c(2,3,5) %/% c(2,3): 1" "c(2,3,5) %/% c(2,3): 1" "c(2,3,5) %/% c(2,3): 2"


### Practice Task 2: Integer Division
Perform integer division of the vector `c(10, 15, 22, 30)` by `c(3, 4)`.

In [ ]:
# Solution to Practice Task 2
vec1 <- c(10, 15, 22, 30)
vec2 <- c(3, 4)
result <- vec1 %/% vec2
print(result)

[1] 3 3 7 7


## 3. Modulo Division

In [ ]:
print('--- Modulo Division Examples (%%) ---')

# Scalar modulo division
print(paste('2 %% 2:', 2 %% 2))
print(paste('3 %% 2:', 3 %% 2))
print(paste('7 %% 3:', 7 %% 3))
print(paste('7 %% 4:', 7 %% 4))

# Vector modulo division
print(paste('c(2,3,5,7) %% 2:', c(2,3,5,7) %% 2))
print(paste('c(2,3,5,7) %% c(2,3):', c(2,3,5,7) %% c(2,3))) # Recycling c(2,3)
print(paste('c(2,3,5) %% c(2,3):', c(2,3,5) %% c(2,3))) # Recycling c(2,3), warning due to unequal lengths

[1] "--- Modulo Division Examples (%%) ---"
[1] "2 %% 2: 0"
[1] "3 %% 2: 1"
[1] "7 %% 3: 1"
[1] "7 %% 4: 3"
[1] "c(2,3,5,7) %% 2: 0" "c(2,3,5,7) %% 2: 1" "c(2,3,5,7) %% 2: 1"
[4] "c(2,3,5,7) %% 2: 1"
[1] "c(2,3,5,7) %% c(2,3): 0" "c(2,3,5,7) %% c(2,3): 0"
[3] "c(2,3,5,7) %% c(2,3): 1" "c(2,3,5,7) %% c(2,3): 1"


Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”


[1] "c(2,3,5) %% c(2,3): 0" "c(2,3,5) %% c(2,3): 0" "c(2,3,5) %% c(2,3): 1"


### Practice Task 3: Modulo Division
Find the remainder when each element of `c(11, 16, 23, 31)` is divided by `c(3, 5)`.

In [ ]:
# Solution to Practice Task 3
vec1 <- c(11, 16, 23, 31)
vec2 <- c(3, 5)
result <- vec1 %% vec2
print(result)

[1] 2 1 2 1


## 4. Built-in Functions

In [ ]:
print('--- Built-in Functions Examples ---')

# max(), min()
print(paste('max(5, 10, 2):', max(5, 10, 2))) # Multiple scalar arguments
print(paste('max(c(5, 10, 2)):', max(c(5, 10, 2)))) # Vector argument
print(paste('min(5, 10, 2):', min(5, 10, 2)))
print(paste('min(c(5, 10, 2)):', min(c(5, 10, 2))))

# mean()
print(paste('mean(c(1,2,3,4,5)):', mean(c(1,2,3,4,5))))

# abs()
print(paste('abs(-5):', abs(-5)))
print(paste('abs(c(-1, 0, 1)):', abs(c(-1, 0, 1))))

# sqrt()
print(paste('sqrt(9):', sqrt(9)))
print(paste('sqrt(c(4, 9, 16)):', sqrt(c(4, 9, 16))))

# sum()
print(paste('sum(c(1,2,3)):', sum(c(1,2,3))))

# prod()
print(paste('prod(c(1,2,3)):', prod(c(1,2,3))))

# round()
print(paste('round(3.14159, 2):', round(3.14159, 2)))
print(paste('round(c(3.1, 3.5, 3.9)):', round(c(3.1, 3.5, 3.9))))

# floor()
print(paste('floor(3.7):', floor(3.7)))
print(paste('floor(c(3.1, 3.9, -2.5)):', floor(c(3.1, 3.9, -2.5))))

# ceiling()
print(paste('ceiling(3.1):', ceiling(3.1)))
print(paste('ceiling(c(3.1, 3.9, -2.5)):', ceiling(c(3.1, 3.9, -2.5))))

# log(), log10(), log2(), exp()
print(paste('log(10):', log(10))) # Natural logarithm
print(paste('log10(100):', log10(100)))
print(paste('log2(8):', log2(8)))
print(paste('exp(1):', exp(1))) # e^1

# Trigonometric functions (angles in radians)
print(paste('sin(pi/2):', sin(pi/2)))
print(paste('cos(pi):', cos(pi)))
print(paste('tan(pi/4):', tan(pi/4)))

# Inverse trigonometric functions (returns radians)
print(paste('asin(1):', asin(1)))
print(paste('acos(0):', acos(0)))
print(paste('atan(1):', atan(1)))

# Hyperbolic functions
print(paste('sinh(1):', sinh(1)))
print(paste('cosh(0):', cosh(0)))
print(paste('tanh(0):', tanh(0)))

# Inverse hyperbolic functions
print(paste('asinh(0):', asinh(0)))
print(paste('acosh(1):', acosh(1)))
print(paste('atanh(0):', atanh(0)))

[1] "--- Built-in Functions Examples ---"
[1] "max(5, 10, 2): 10"
[1] "max(c(5, 10, 2)): 10"
[1] "min(5, 10, 2): 2"
[1] "min(c(5, 10, 2)): 2"
[1] "mean(c(1,2,3,4,5)): 3"
[1] "abs(-5): 5"
[1] "abs(c(-1, 0, 1)): 1" "abs(c(-1, 0, 1)): 0" "abs(c(-1, 0, 1)): 1"
[1] "sqrt(9): 3"
[1] "sqrt(c(4, 9, 16)): 2" "sqrt(c(4, 9, 16)): 3" "sqrt(c(4, 9, 16)): 4"
[1] "sum(c(1,2,3)): 6"
[1] "prod(c(1,2,3)): 6"
[1] "round(3.14159, 2): 3.14"
[1] "round(c(3.1, 3.5, 3.9)): 3" "round(c(3.1, 3.5, 3.9)): 4"
[3] "round(c(3.1, 3.5, 3.9)): 4"
[1] "floor(3.7): 3"
[1] "floor(c(3.1, 3.9, -2.5)): 3"  "floor(c(3.1, 3.9, -2.5)): 3" 
[3] "floor(c(3.1, 3.9, -2.5)): -3"
[1] "ceiling(3.1): 4"
[1] "ceiling(c(3.1, 3.9, -2.5)): 4"  "ceiling(c(3.1, 3.9, -2.5)): 4" 
[3] "ceiling(c(3.1, 3.9, -2.5)): -2"
[1] "log(10): 2.30258509299405"
[1] "log10(100): 2"
[1] "log2(8): 3"
[1] "exp(1): 2.71828182845905"
[1] "sin(pi/2): 1"
[1] "cos(pi): -1"
[1] "tan(pi/4): 1"
[1] "asin(1): 1.5707963267949"
[1] "acos(0): 1.5707963267949"
[1] "atan(1):

### Practice Task 4: Built-in Functions
1.  Calculate the sum of squares of the vector `c(1, 2, 3, 4, 5)`.
2.  Find the `log10` of `1000`.

In [ ]:
# Solution to Practice Task 4
# Part 1: Sum of squares
vec_sq <- c(1, 2, 3, 4, 5)
sum_of_squares <- sum(vec_sq^2)
print(paste('Sum of squares:', sum_of_squares))

# Part 2: log10 of 1000
log_val <- log10(1000)
print(paste('log10(1000):', log_val))

[1] "Sum of squares: 55"
[1] "log10(1000): 3"


## 5. Assignments

In [ ]:
print('--- Assignment Examples ---')

# Assignment using =
x1 = c(1,2,3,4)
print(paste('x1:', paste(x1, collapse = ', ')))

# Assignment using <-
x2 <- x1^2
print(paste('x2 (x1 squared):', paste(x2, collapse = ', ')))

# Calculations with assignments
# Demonstrate complex calculation
vector_op <- c(1,2,3,4)
sum_vec <- sum(vector_op)
prod_vec <- prod(c(1,2))

result1 <- vector_op + sum_vec * prod_vec
print(paste('c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2)):', paste(result1, collapse = ', ')))

result2 <- abs(vector_op - sum_vec * prod_vec)
print(paste('abs(c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2))):', paste(result2, collapse = ', ')))


[1] "--- Assignment Examples ---"
[1] "x1: 1, 2, 3, 4"
[1] "x2 (x1 squared): 1, 4, 9, 16"
[1] "c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2)): 21, 22, 23, 24"
[1] "abs(c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2))): 19, 18, 17, 16"


### Practice Task 5: Assignments
Assign the vector `c(5, 10, 15)` to a variable `my_vector`. Then, calculate `my_vector` multiplied by the `mean` of `my_vector`.

In [ ]:
# Solution to Practice Task 5
my_vector <- c(5, 10, 15)
mean_my_vector <- mean(my_vector)
calculated_result <- my_vector * mean_my_vector
print(paste('Original vector:', paste(my_vector, collapse = ', ')))
print(paste('Mean of vector:', mean_my_vector))
print(paste('Calculated result:', paste(calculated_result, collapse = ', ')))


[1] "Original vector: 5, 10, 15"
[1] "Mean of vector: 10"
[1] "Calculated result: 50, 100, 150"


## 6. Matrices

In [ ]:
print('--- Matrix Creation Examples ---')

# Default matrix creation (column-wise filling)
mat_default <- matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
print('Matrix (default, column-wise):')
print(mat_default)

# Explicitly column-wise filling
mat_colwise <- matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=FALSE)
print('Matrix (byrow=FALSE, column-wise):')
print(mat_colwise)

# Row-wise filling
mat_rowwise <- matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=TRUE)
print('Matrix (byrow=TRUE, row-wise):')
print(mat_rowwise)

# Demonstrating default fill direction
cat('\nDefault matrix fill direction is column-wise, which means data fills the first column, then the second, and so on.\n')
cat('When `byrow=TRUE`, data fills the first row, then the second, and so on.\n')

[1] "--- Matrix Creation Examples ---"
[1] "Matrix (default, column-wise):"
     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8
[1] "Matrix (byrow=FALSE, column-wise):"
     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8
[1] "Matrix (byrow=TRUE, row-wise):"
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8

Default matrix fill direction is column-wise, which means data fills the first column, then the second, and so on.
When `byrow=TRUE`, data fills the first row, then the second, and so on.


### Practice Task 6: Matrix Creation
Create a 3x3 matrix named `my_matrix` with data `c(1, 2, 3, 4, 5, 6, 7, 8, 9)` filled row-wise.

In [ ]:
# Solution to Practice Task 6
my_matrix <- matrix(nrow=3, ncol=3, data=c(1,2,3,4,5,6,7,8,9), byrow=TRUE)
print('My 3x3 matrix filled row-wise:')
print(my_matrix)

[1] "My 3x3 matrix filled row-wise:"
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


## 7. Matrix Properties

In [ ]:
print('--- Matrix Properties Examples ---')

# Create a sample matrix 'x'
x <- matrix(c(10, 20, 30, 40, 50, 60, 70, 80), nrow = 4, ncol = 2, byrow = TRUE)
print('Sample matrix x:')
print(x)

# Accessing elements
print(paste('x[3,2] (element at row 3, column 2):', x[3,2]))

# Dimensions
print(paste('dim(x) (dimensions of x):', paste(dim(x), collapse = 'x')))
print(paste('nrow(x) (number of rows):', nrow(x)))
print(paste('ncol(x) (number of columns):', ncol(x)))

# Mode and Attributes
print(paste('mode(x) (storage mode of x):', mode(x))) # Data type of elements
print('attributes(x) (attributes of x):')
print(attributes(x))

# Type checking and conversion
print(paste('is.matrix(x) (is x a matrix?):', is.matrix(x)))
# For demonstration, converting back to matrix from a similar structure if it weren't a matrix
# as.matrix(x) would return x itself if it's already a matrix
# Example: if y was a data frame, as.matrix(y) would convert it.
# Let's create a data frame for as.matrix demo
df_example <- data.frame(A = 1:2, B = 3:4)
print('\nExample with as.matrix on a data.frame:')
print(df_example)
print(as.matrix(df_example))

[1] "--- Matrix Properties Examples ---"
[1] "Sample matrix x:"
     [,1] [,2]
[1,]   10   20
[2,]   30   40
[3,]   50   60
[4,]   70   80
[1] "x[3,2] (element at row 3, column 2): 60"
[1] "dim(x) (dimensions of x): 4x2"
[1] "nrow(x) (number of rows): 4"
[1] "ncol(x) (number of columns): 2"
[1] "mode(x) (storage mode of x): numeric"
[1] "attributes(x) (attributes of x):"
$dim
[1] 4 2

[1] "is.matrix(x) (is x a matrix?): TRUE"
[1] "\nExample with as.matrix on a data.frame:"
  A B
1 1 3
2 2 4
     A B
[1,] 1 3
[2,] 2 4


### Practice Task 7: Matrix Properties
Create a 2x3 matrix `m` with any numeric data. Find its dimensions, number of rows, and number of columns. Also, check if it is a matrix.

In [ ]:
# Solution to Practice Task 7
m <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3)
print('Matrix m:')
print(m)
print(paste('Dimensions of m:', paste(dim(m), collapse = 'x')))
print(paste('Number of rows in m:', nrow(m)))
print(paste('Number of columns in m:', ncol(m)))
print(paste('Is m a matrix?', is.matrix(m)))

[1] "Matrix m:"
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] "Dimensions of m: 2x3"
[1] "Number of rows in m: 2"
[1] "Number of columns in m: 3"
[1] "Is m a matrix? TRUE"


## 8. Matrix Help and Related Functions

In [ ]:
print('--- Matrix Help and Related Functions Examples ---')

# Accessing help documentation for matrix
# help("matrix") # Uncomment and run to see the help page
cat('Run `help("matrix")` in a separate cell to view the documentation for the matrix function.\n')

# Demonstrating matrix parameters: data, nrow, ncol, byrow, dimnames
# Example with dimnames
matrix_with_names <- matrix(data = 1:6, nrow = 2, ncol = 3,
                          dimnames = list(c('Row1', 'Row2'), c('ColA', 'ColB', 'ColC')))
print('\nMatrix with dimnames:')
print(matrix_with_names)

# Demonstrating recycling when data contains too few elements
# The data vector is `1:5` (5 elements), but the matrix is 3x3 (9 elements).
# R will recycle `1:5` to fill the remaining 4 positions (1, 2, 3, 4).
matrix_recycling <- matrix(data = 1:5, nrow = 3, ncol = 3)
print('\nMatrix demonstrating data recycling (data = 1:5, matrix is 3x3):')
print(matrix_recycling)
cat('Notice how the numbers 1 to 5 are repeated (recycled) to fill the 3x3 matrix.\n')

# Another example of recycling with warning
matrix_recycling_warning <- matrix(data = 1:4, nrow = 3, ncol = 3) # 4 elements for 9 spots, not a multiple
print('\nMatrix demonstrating data recycling with warning (data = 1:4, matrix is 3x3):')
print(matrix_recycling_warning)
cat('A warning is typically issued when the length of the data is not a multiple of the number of elements needed for the matrix.\n')

[1] "--- Matrix Help and Related Functions Examples ---"
Run `help("matrix")` in a separate cell to view the documentation for the matrix function.
[1] "\nMatrix with dimnames:"
     ColA ColB ColC
Row1    1    3    5
Row2    2    4    6


Warning message in matrix(data = 1:5, nrow = 3, ncol = 3):
“data length [5] is not a sub-multiple or multiple of the number of rows [3]”


[1] "\nMatrix demonstrating data recycling (data = 1:5, matrix is 3x3):"
     [,1] [,2] [,3]
[1,]    1    4    2
[2,]    2    5    3
[3,]    3    1    4
Notice how the numbers 1 to 5 are repeated (recycled) to fill the 3x3 matrix.


Warning message in matrix(data = 1:4, nrow = 3, ncol = 3):
“data length [4] is not a sub-multiple or multiple of the number of rows [3]”


[1] "\nMatrix demonstrating data recycling with warning (data = 1:4, matrix is 3x3):"
     [,1] [,2] [,3]
[1,]    1    4    3
[2,]    2    1    4
[3,]    3    2    1
A warning is typically issued when the length of the data is not a multiple of the number of elements needed for the matrix.


### Practice Task 8: Matrix with `dimnames` and Recycling
1.  Create a 2x2 matrix with row names "A", "B" and column names "X", "Y", containing data `c(10, 20, 30, 40)`.
2.  Create a 3x2 matrix using data `c(1, 2, 3)` and observe the recycling behavior.

In [ ]:
# Solution to Practice Task 8
# Part 1: Matrix with dimnames
matrix_dimnames_task <- matrix(data = c(10, 20, 30, 40), nrow = 2, ncol = 2,
                               dimnames = list(c('A', 'B'), c('X', 'Y')))
print('Matrix with dimnames:')
print(matrix_dimnames_task)

# Part 2: Matrix with recycling
matrix_recycling_task <- matrix(data = c(1, 2, 3), nrow = 3, ncol = 2)
print('\nMatrix with recycling (data = c(1,2,3), 3x2 matrix):')
print(matrix_recycling_task)

[1] "Matrix with dimnames:"
   X  Y
A 10 30
B 20 40
[1] "\nMatrix with recycling (data = c(1,2,3), 3x2 matrix):"
     [,1] [,2]
[1,]    1    1
[2,]    2    2
[3,]    3    3


## 9. Matrix vs Data Frame

In [ ]:
print('--- Matrix vs Data Frame Examples ---')

# Load the warpbreaks dataset
data(warpbreaks)
print('\nFirst few rows of warpbreaks data:')
print(head(warpbreaks))

# Check if warpbreaks is a matrix
print(paste('is.matrix(warpbreaks) (Is warpbreaks a matrix?):', is.matrix(warpbreaks)))

# Display first 10 rows of warpbreaks (it's a data.frame)
print('\nwarpbreaks[1:10,] (first 10 rows):')
print(warpbreaks[1:10,])

# Convert first 10 rows to a matrix and display
as_matrix_warpbreaks <- as.matrix(warpbreaks[1:10,])
print('\nas.matrix(warpbreaks[1:10,]) (first 10 rows converted to matrix):')
print(as_matrix_warpbreaks)

# Check the type after conversion
print(paste('is.matrix(as_matrix_warpbreaks) (Is the converted object a matrix?):', is.matrix(as_matrix_warpbreaks)))

[1] "--- Matrix vs Data Frame Examples ---"
[1] "\nFirst few rows of warpbreaks data:"
  breaks wool tension
1     26    A       L
2     30    A       L
3     54    A       L
4     25    A       L
5     70    A       L
6     52    A       L
[1] "is.matrix(warpbreaks) (Is warpbreaks a matrix?): FALSE"
[1] "\nwarpbreaks[1:10,] (first 10 rows):"
   breaks wool tension
1      26    A       L
2      30    A       L
3      54    A       L
4      25    A       L
5      70    A       L
6      52    A       L
7      51    A       L
8      26    A       L
9      67    A       L
10     18    A       M
[1] "\nas.matrix(warpbreaks[1:10,]) (first 10 rows converted to matrix):"
   breaks wool tension
1  "26"   "A"  "L"    
2  "30"   "A"  "L"    
3  "54"   "A"  "L"    
4  "25"   "A"  "L"    
5  "70"   "A"  "L"    
6  "52"   "A"  "L"    
7  "51"   "A"  "L"    
8  "26"   "A"  "L"    
9  "67"   "A"  "L"    
10 "18"   "A"  "M"    
[1] "is.matrix(as_matrix_warpbreaks) (Is the converted object a matrix?): T

### Practice Task 9: Matrix vs Data Frame
Create a small data frame with two columns: `name` (character) and `age` (numeric). Then, try to convert it into a matrix and observe the result, especially the data type.

In [ ]:
# Solution to Practice Task 9
# Create a data frame
my_df <- data.frame(name = c('Alice', 'Bob', 'Charlie'), age = c(25, 30, 22))
print('Original Data Frame:')
print(my_df)
print(paste('Mode of Data Frame:', mode(my_df)))
print(paste('Is my_df a data.frame?', is.data.frame(my_df)))

# Convert to matrix
my_matrix_from_df <- as.matrix(my_df)
print('\nConverted to Matrix:')
print(my_matrix_from_df)
print(paste('Mode of converted Matrix:', mode(my_matrix_from_df)))
print(paste('Is my_matrix_from_df a matrix?', is.matrix(my_matrix_from_df)))
cat('\nNotice how the numeric `age` column became character after conversion to a matrix, because all elements in a matrix must be of the same type.')

[1] "Original Data Frame:"
     name age
1   Alice  25
2     Bob  30
3 Charlie  22
[1] "Mode of Data Frame: list"
[1] "Is my_df a data.frame? TRUE"
[1] "\nConverted to Matrix:"
     name      age 
[1,] "Alice"   "25"
[2,] "Bob"     "30"
[3,] "Charlie" "22"
[1] "Mode of converted Matrix: character"
[1] "Is my_matrix_from_df a matrix? TRUE"

Notice how the numeric `age` column became character after conversion to a matrix, because all elements in a matrix must be of the same type.